core_nav_map =    {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "up",
								"horiz": "stopped"},
					 "upright": {"vert": "up",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "right"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
							   "horiz":  "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "left"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "left"},
				   "downright": {"vert": "right",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz": "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "up",
								"horiz": "left"},
					 "upright": {"vert": "up",
								"horiz": "up"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "down"},
				   "downright": {"vert": "stopped",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "up"},
					 "upright": {"vert": "stopped",
								"horiz": "up"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "down",
								"horiz": "down"},
				   "downright": {"vert": "down",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}}}
								
								
top_nav_map =     {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "right",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "right"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "left"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "left"},
				   "downright": {"vert": "right",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz": "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "left"},
					 "upright": {"vert": "stopped",
								"horiz": "right"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "down"},
				   "downright": {"vert": "stopped",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "left"},
					 "upright": {"vert": "stopped",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "down",
								"horiz": "down"},
				   "downright": {"vert": "down",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}}}
					
topleft_nav_map = {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "right",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "down",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "left"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz": "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "left"},
					 "upright": {"vert": "stopped",
								"horiz": "right"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "down"},
				   "downright": {"vert": "stopped",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "left"},
					 "upright": {"vert": "stopped",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "down",
								"horiz": "down"},
				   "downright": {"vert": "down",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}}}

topright_nav_map = {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "right",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "down",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "left"},
				   "downright": {"vert": "down",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz": "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "left"},
					 "upright": {"vert": "stopped",
								"horiz": "right"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "down"},
				   "downright": {"vert": "stopped",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "left"},
					 "upright": {"vert": "stopped",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "down",
								"horiz": "down"},
				   "downright": {"vert": "down",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz":  "right"}}}


bottom_nav_map = {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "up",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "right"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "left"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "left"},
				   "downright": {"vert": "right",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz":  "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "up",
								"horiz": "left"},
					 "upright": {"vert": "up",
								"horiz": "up"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "up"},
					 "upright": {"vert": "stopped",
								"horiz": "up"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}}}


bottomleft_nav_map = {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "up",
								"horiz": "stopped"},
					 "upright": {"vert": "up",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "right"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "up",
								"horiz": "stopped"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz":  "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "up",
								"horiz": "up"},
					 "upright": {"vert": "up",
								"horiz": "up"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "up"},
					 "upright": {"vert": "stopped",
								"horiz": "up"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}}}


bottomright_nav_map = {"up": {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "up",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "right"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "left"},
					 "upright": {"vert": "up",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "left"},
				   "downright": {"vert": "right",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz":  "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "up",
								"horiz": "left"},
					 "upright": {"vert": "up",
								"horiz": "up"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "up"},
					 "upright": {"vert": "stopped",
								"horiz": "up"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}}}


left_nav_map = {"up": {"up": {"vert": "up",
								"horiz": "stopped"}, 
					  "upleft": {"vert": "up",
								"horiz": "stopped"},
					 "upright": {"vert": "up",
								"horiz": "right"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "right",
								"horiz": "right"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "up",
								"horiz": "stopped"},
					 "upright": {"vert": "right",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "stopped"},
				   "downright": {"vert": "down",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz":  "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "up",
								"horiz": "up"},
					 "upright": {"vert": "up",
								"horiz": "up"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "down"},
				   "downright": {"vert": "stopped",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "up"},
					 "upright": {"vert": "stopped",
								"horiz": "up"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "down",
								"horiz": "down"},
				   "downright": {"vert": "down",
								"horiz": "right"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz":  "right"}}}


right_nav_map = {"up": {"up": {"vert": "up",
								"horiz":"stopped" },
					  "upleft": {"vert": "left",
								"horiz": "stopped"},
					 "upright": {"vert": "up",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "left",
								"horiz": "stopped"},
				   "downright": {"vert": "down",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "stopped"},
					   "right": {"vert": "right",
								"horiz": "right"}},
					
			"down":      {"up": {"vert": "up",
								"horiz": "stopped"},
					  "upleft": {"vert": "left",
								"horiz": "left"},
					 "upright": {"vert": "up",
								"horiz": "stopped"},
						"down": {"vert": "down",
								"horiz": "stopped"},
					"downleft": {"vert": "down",
								"horiz": "left"},
				   "downright": {"vert": "down",
								"horiz": "stopped"},
						"left": {"vert": "left",
								"horiz": "left"},
					   "right": {"vert": "right",
								"horiz":  "stopped"}},
		
			"left":      {"up": {"vert": "up",
								"horiz": "up"},
					  "upleft": {"vert": "up",
								"horiz": "left"},
					 "upright": {"vert": "up",
								"horiz": "up"},
						"down": {"vert": "stopped",
								"horiz": "down"},
					"downleft": {"vert": "stopped",
								"horiz": "left"},
				   "downright": {"vert": "stopped",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz": "right"}},

			"right":     {"up": {"vert": "stopped",
								"horiz": "up"},
					  "upleft": {"vert": "stopped",
								"horiz": "up"},
					 "upright": {"vert": "stopped",
								"horiz": "up"},
						"down": {"vert": "down",
								"horiz": "down"},
					"downleft": {"vert": "down",
								"horiz": "down"},
				   "downright": {"vert": "down",
								"horiz": "down"},
						"left": {"vert": "stopped",
								"horiz": "left"},
					   "right": {"vert": "stopped",
								"horiz":  "right"}}}
								
def choose_nav_map(car):
	if car.rect.centerx < 160 and car.rect.centery < 160:
		correct_map = topleft_nav_map
	elif car.rect.centerx < 160 and car.rect.centery > 480:
		correct_map = bottomleft_nav_map			
	elif car.rect.centerx > 736 and car.rect.centery < 160:
		correct_map = topright_nav_map
	elif car.rect.centerx > 736 and car.rect.centery > 480:
		correct_map = bottomright_nav_map
	elif car.rect.centerx < 160:
		correct_map = left_nav_map
	elif car.rect.centerx > 736:
		correct_map = right_nav_map
	elif car.rect.centery < 160:
		correct_map = top_nav_map
	elif car.rect.centery > 480:
		correct_map = bottom_nav_map
	else:
		correct_map = core_nav_map
	return correct_map
				
	
				